### ISSUE TITLE
Xss vunarability

### ISSUE THREAD

**Issue by EchoQuill** [TheAxes/Advance-Auto-Owo#2]
steps of reproduction:-
1) open https://owo-captcha-solver.vercel.app/captcha_solution
2) put "<script>alert('XSS Attack!');</script>" as input
3) press submit.
![Screenshot_20240811-113957_Chrome.png](https://github.com/user-attachments/assets/5e5fbfbf-0215-4df3-8ef1-129f6806aa0a)

![Screenshot_20240811-113947_Chrome.png](https://github.com/user-attachments/assets/1fd1826e-304b-40f1-b6ea-ee76e424543e)

thankyou!

**Comment by EchoQuill** [comment]
And yeah, that’s a really curious solution you found for using Scrapy to solve CAPTCHAs right there, but I don’t recommend doing the same

**Comment by TheAxes** [comment]
> steps of reproduction:-
> 
> 1. open https://owo-captcha-solver.vercel.app/captcha_solution
> 2. put "<script>alert('XSS Attack!');</script>" as input
> 3. press submit.
>    ![Screenshot_20240811-113957_Chrome.png](https://private-user-images.githubusercontent.com/92152439/356854488-5e5fbfbf-0215-4df3-8ef1-129f6806aa0a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDQyOTksIm5iZiI6MTcyMzQ0Mzk5OSwicGF0aCI6Ii85MjE1MjQzOS8zNTY4NTQ0ODgtNWU1ZmJmYmYtMDIxNS00ZGYzLThlZjEtMTI5ZjY4MDZhYTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA2MjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJkMDA1ODc1MWJiZGFlMjg2ODgwZmNjM2EzYzEzNzk4Mzg1ODFiMmFiMzA1OGVlOWIwZTc1ODM1OTZhNmI2MWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.czAYaTbsmSvjynHDIWPpU8e7A51vVM6IoDpmgHZrd6M)
> 
> ![Screenshot_20240811-113947_Chrome.png](https://private-user-images.githubusercontent.com/92152439/356854489-1fd1826e-304b-40f1-b6ea-ee76e424543e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM0NDQyOTksIm5iZiI6MTcyMzQ0Mzk5OSwicGF0aCI6Ii85MjE1MjQzOS8zNTY4NTQ0ODktMWZkMTgyNmUtMzA0Yi00MGYxLWI2ZWEtZWU3NmU0MjQ1NDNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODEyVDA2MjYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyNmVlNGM3ZjNkM2I2ZmMxMWViOGQwYWMwNDY5ZGI4MDc3MmM2OTI3NDA3NmM2MDA4MjliODZiNmFmM2E3N2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MavrjQ6v6kGLJP8zo_IWA9YuM8PUrSBq_U4gUXNgBc4)
> 
> thankyou!

Thanks for letting me this i made it safe now!
